-- =============================================================================
-- migration_cuenta_autoservicio.sql
-- Desarrollado por Marco Antonio Posligua San Martín
--
-- Módulo de administración de la propia cuenta en Atlas:
--   * El usuario (admin, socio, secretaria, profesor, psicólogo) mantiene sus datos.
--   * Cambia su clave verificando la anterior.
--   * Si la olvidó, el administrador la restablece con una clave temporal de un
--     solo uso; el sistema obliga a cambiarla al entrar.
--
-- Idempotente. Aplicar en el editor SQL de Supabase.
-- =============================================================================

-- Datos de contacto que el propio usuario mantiene
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS telefono text;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS cargo    text;

-- Control de clave temporal
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS debe_cambiar_clave    boolean NOT NULL DEFAULT false;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS clave_temporal_expira timestamptz;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS clave_actualizada_en  timestamptz;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS clave_reseteada_por   bigint;

-- Bitácora de restablecimientos (nunca guarda la clave, solo el hecho)
CREATE TABLE IF NOT EXISTS usuarios_clave_log (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id    bigint NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  accion        text   NOT NULL,          -- 'reset_admin' | 'cambio_propio'
  ejecutado_por bigint,
  ip            text,
  created_at    timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_usuarios_clave_log_usuario
  ON usuarios_clave_log (usuario_id, created_at DESC);

-- La app entra con service_role; RLS cerrada como el resto del esquema.
ALTER TABLE usuarios_clave_log ENABLE ROW LEVEL SECURITY;
